# Neuroconductor Template no ANTs
language: r
cache: packages
warnings_are_errors: true
cran: http://cran.rstudio.com
dist: trusty


addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev      
    - libfftw3-dev
env:
  global: 
    - RGL_USE_NULL=TRUE
    - PROJECT_NAME=neuroconductor
    - DISPLAY=:99.0
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: --as-cran --install-args=--build

before_install:
  - ulimit -n 2048
  - export PROJ_DIR=`basename $PWD`    
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - start_xvfb ;
  - export rver=`r_version`; echo $rver ;
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      no_open_mp ; 
    fi
  - jags_install ;  
  - v8_install ;
  - dcmtk_install ;
  - remove_neuroc_packages ;
  - cat DESCRIPTION
  - install_remotes_no_dep
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - echo "Package Name is $PACKAGE_NAME"
  - if [[ "${PACKAGE_NAME}" == "waveslim" ]]; 
    then
      fftw_install ;
    fi
  - if [[ "${PACKAGE_NAME}" == "dti" || "${PACKAGE_NAME}" == "qMRI" ]]; 
    then
      gsl_install ;
    fi
  - fname=gsl-2.5.tar.gz && tar -zxvf ${fname};
  - stub=`echo ${fname} | sed "s/.tar.gz//"` ;
  - rm ${fname};
  - cd ${stub} ;
  - ./configure && make && make check && make install ;
  - cd .. && rm -rf ${stub} ; 
  - gsl-config --version ; gsl-config  --cflags; gsl-config  --libs  
  - if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; 
    then
      shopt -s expand_aliases ;
      x=`Rscript -e "cat(Sys.which('R'))"` ;
      echo "reset R" ;
      alias R="travis_wait 100 ${x}" ;
    fi
  - install_python_requirements ;    
  - R CMD javareconf ;  
  - pwd;
  - cat DESCRIPTION; 

after_success:
  - dump_logs

after_failure:
  - dump_logs

